package fhj.ima.com.example.coronainfoapp

import com.squareup.moshi.JsonClass

class ampelfarben (
    val stufe: String,
    val beschränkungen: List<String>,
    val color: String
)

@JsonClass(generateAdapter = true)
class epikurve(
    val Datum: String,
    val Fälle_gesamt: Int
    /*val Fälle_Zuwachs: String,
    val Tote_v1: String,
    val Tote_v1_Zuwachs: String,
    val Tote_v2: String,
    val Tote_v2_Zuwachs: String,
    val Genesene: String,
    val Genesene_Zuwachs: String,
    val Hospitalisiert: String,
    val Intensivstation: String,
    val IBett_frei: String,
    val IBett_Kapazität: String,
    val Testungen: String,
    val Testungen_Zuwachs: String,
    val Burgenland: String,
    val Burgenland_Tote: String,
    val Burgenland_Genesene: String,
    val Burgenland_Spital: String,
    val Burgenland_Intensiv: String,
    val Burgenland_Tests: String,
    val Kärnten: String,
    val Kärnten_Tote: String,
    val Kärnten_Genesene: String,
    val Kärnten_Spital: String,
    val Kärnten_Intensiv: String,
    val Kärnten_Tests: String,
    val Niederösterreich: String,
    val Niederösterreich_Tote: String,
    val Niederösterreich_Genesene: String,
    val Niederösterreich_Spital: String,
    val Niederösterreich_Intensiv: String,
    val Niederösterreich_Tests: String,
    val Oberösterreich: String,
    val Oberösterreich_Tote: String,
    val Oberösterreich_Genesene: String,
    val Oberösterreich_Spital: String,
    val Oberösterreich_Intensiv: String,
    val Oberösterreich_Tests: String,
    val Salzburg: String,
    val Salzburg_Tote: String,
    val Salzburg_Genesene: String,
    val Salzburg_Spital: String,
    val Salzburg_Intensiv: String,
    val Salzburg_Tests: String,
    val Steiermark: String,
    val Steiermark_Tote: String,
    val Steiermark_Genesene: String,
    val Steiermark_Spital: String,
    val Steiermark_Intensiv: String,
    val Steiermark_Tests: String,
    val Tirol: String,
    val Tirol_Tote: String,
    val Tirol_Genesene: String,
    val Tirol_Spital: String,
    val Tirol_Intensiv: String,
    val Tirol_Tests: String,
    val Vorarlberg: String,
    val Vorarlberg_Tote: String,
    val Vorarlberg_Genesene: String,
    val Vorarlberg_Spital: String,
    val Vorarlberg_Intensiv: String,
    val Vorarlberg_Tests: String,
    val Wien: String,
    val Wien_Tote: String,
    val Wien_Genesene: String,
    val Wien_Spital: String,
    val Wien_Intensiv: String,
    val Wien_Tests: String*/

)